config/routes.rb
Rails.application.routes.draw do
  #root route
root 'posts#index', as: 'home'

#regular route
get 'about' => 'pages#about', as: 'about'

#creates all of our RESTful routes
resources :posts do
resources :comments

end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  validates :title, presence: true,
                    length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
http_basic_authenticate_with name: "Joe", password: "1234", only: [:destroy]
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end


  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end


    private def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @title = "About Us";
    @content = "This is the About page"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
http_basic_authenticate_with name: "Joe", password: "1234", except: [:index, :show]
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end


  def new
    @post = Post.new
  end

  def create
    # render plain: params[:post].inspect
    @post = Post.new(post_params)

    if(@post.save)
    redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
      @post = Post.find(params[:id])

      if(@post.update(post_params))
      redirect_to @post
      else
        render 'edit'
      end
  end

  def destroy
        @post = Post.find(params[:id])
        @post.destroy

        redirect_to posts_path

  end


    private def post_params
    params.require(:post).permit(:title, :body)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<h3>Comments</h3>
<% @post.comments.each do |comment| %>
  <div class="card card-body bg-light p-3">
    <p><strong><%= comment.username %></strong>
        : <%= comment.body %>
        <%= link_to "[x]", [comment.post, comment],
                          method: :delete,
                          data: {confirm: 'Really?'},
                          :class => "radio-inline" %>
    </p>
  </div>
<% end %>

app/views/comments/_form.html.erb
<h3>Add Comment</h3>
<%= form_for ([@post, @post.comments.build]) do |f| %>

<p>
  <%= f.label :username %><br>
  <%= f.text_field( :username, {:class => 'form-control'} )%>
</p>
<p>
  <%= f.label :body %>
  <br>
  <%= f.text_area( :body, {:class => 'form-control'})%>
</p>

<p>
  <%= f.submit({:class => 'btn btn-outline-primary'}) %>
</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BaconStories</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Cinzel|Vidaloka&display=swap" rel="stylesheet">


    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body><!-- Image and text -->





    <nav class="navbar navbar-expand-md navbar-light bg-light" style=" background-image: linear-gradient(90deg, rgb(22, 37, 50), rgb(38, 87, 59));!important">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse float-right" id="navbarsExampleDefault">

    <a id="bacon" class="navbar-brand" href="/posts">BaconStories</a>
    <ul class="navbar-nav mx-auto">
      <li class="nav-item active">

      </li>
      <h4 ><%= link_to "Home", home_path %></h4>
    </ul>
    <ul class="navbar-nav float-right">
      <li class="nav-item active">
        <h4><%= link_to "Create Post", new_post_path %></h4>
      </li>
    </ul>
  </div>
</nav>
<div class="container">
  <%= yield %>
</div>

  </body>
</html>

app/views/pages/about.html.erb
<h1> <%= @title %> </h1>
<p> <%= @content %> </p>

app/views/posts/edit.html.erb
<div class="container">
  <h1 class="text-center">Edit Post</h1>
  <%= form_for :post, url: post_path(@post), method: :patch do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    <%= f.label :title %>
    <br>
    <%= f.text_field( :title, {:class => 'form-control'} )%>
  </p>

  <p>
    <%= f.label :body %>
    <br>
    <%= f.text_area( :body, {:class => 'form-control'})%>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-warning'}) %>
  </p>
<% end %>

</div>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>


    <div class="container">

      <div id= "bgimg" class="jumbotron jumbotron-fluid">
        <div class="container" >
        <h1 id="stories" class="text-center">Bacon Stories</h1>

        </div>
  </div>

      <% @posts.each do |post| %>

        <div class="card card-body bg-light text-center">
          <h3><%= post.title %></h3>
          <p><%= post.body %></p>
          <div class="">
            <%= link_to "Read More", post_path(post), :class => "btn btn-outline-primary" %>
          </div>

        </div>

      <% end %>


  </body>
</html>

app/views/posts/new.html.erb
<div class="container">
  <h1 class="text-center">Add Post</h1>
  <%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    <%= f.label :title %>
    <br>
    <%= f.text_field( :title, {:class => 'form-control'} )%>
  </p>

  <p>
    <%= f.label :body %>
    <br>
    <%= f.text_area( :body, {:class => 'form-control'})%>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-warning'}) %>
  </p>
<% end %>



<canvas id="canvas" width="1000" height="800"></canvas>

</div>

app/views/posts/show.html.erb
<div class="container text-center">
  <h2> <%= @post.title %> </h2>
  <p>  <%=  @post.body %> </p>
  <%= link_to "Edit", edit_post_path(@post),:class => "btn btn-outline-success" %>
  <%= link_to "Delete", post_path(@post),
                    method: :delete,
                    data: {confirm: 'Really?'},
                    :class => "btn btn-outline-danger" %>
</div>

<hr>

<%= render 'comments/comments' %>
<%= render 'comments/form' %>